### ISSUE TITLE
Блокировка

### ISSUE THREAD

**Issue by Proteus86** [interlark/parser-2gis#1]
При работе парсера примерно на 7ой ссылке начинают блокировать АПИ ключ.
Примерно на 100ой ссылке блокировка по IP. 
Нужен механизм прокси .  И обработка повтора запроса при ошибке блокировки ключа или таймауту . 
Так же замечены ошибки парсера ответа json.
Так же имеет смысл помечать ссылки отработанные корректно в парсере . Чтобы можно продолжить далее .

**Comment by interlark** [comment]
https://github.com/interlark/parser-2gis/blob/29c22aaf8cd18dcdf88407c8d7040cbede0a2fef/parser_2gis/parser/parser.py#L181

Ссылка 3 раза пытается получить ответ сервера -- если ключ устарел или был заблокирован, он должен обновиться в следующей итерации.

Блокировку русского IP не видел ещё, хотя много кому скидывал этот парсер. Нерусские IP могут работать нестабильно. Если блокируется адрес, возможно есть смысл в опциях уменьшить скорость парсинга.

На всех моих тестовых случаях никакой блокировки не видел. Если скинешь URL-сет, то посмотрю.

**Comment by interlark** [comment]
Закрываю, т.к. ответа нет. Возможно, стоит в вики написать, что антибот у 2GIS не любит иностранные IP.

**Comment by Proteus86** [comment]
Прошу прощения не мог отписать ранее. 
Проверил все еще раз , но не через VPN . Все отработало корректно. 
1500 с лишним ссылок обработаны и сохранены.
