### ISSUE TITLE
Что нужно установить, чтобы пользоваться программой?

### ISSUE THREAD

**Issue by BigTolly** [interlark/parser-2gis#11]
Скачал версию для Windows: Parser2GIS.exe
У меня установлена ОС Windows 7 x64, и хром тоже установлен.
При запуске пишет системная ошибка, отсутствует файл  api-ms-win-core-path-l1-1-0.dll,
затем сразу следующая ошибка: не найдет модуль python310.dll

Для работы написано, что требуется только: "Для работы парсера необходимо установить браузер [Google Chrome](https://google.com/chrome)."
Все таки, что еще нужно установить или обновите инструкцию к установке, пожалуйста.

**Comment by interlark** [comment]
Не думал о поддержке Windows 7, Windows 8. Попробуйте эту сборку: https://github.com/interlark/parser-2gis/actions/runs/2779695492

**Comment by BigTolly** [comment]
Спасибо, эта работает.
