### ISSUE TITLE
Сервер ответил с ошибкой

### ISSUE THREAD

**Issue by Teemon666** [interlark/parser-2gis#12]
из лога:
23:39:00.702 | Сервер ответил ошибкой: Authorization error (key is blocked, please contact api@2gis.ru)

Также запрос на https://data.2gis.com/ показывает по категории 311 записей, а парсер выгружает только 57.

**Comment by interlark** [comment]
1) Российский IP используете?
2) Какая ссылка?

**Comment by interlark** [comment]
Подобная ошибка может возникнуть при использовании парсера с нероссийским IP адресом.
Ответа нет, issue закрыт.
