### ISSUE TITLE
Парсинг организаций

### ISSUE THREAD

**Issue by YAGAOFFIT** [interlark/parser-2gis#13]
Приветствую, столкнулся с проблемой, мне надо запарсить организации из определенного здания и у меня не получается это сделать. Есть ли решение этой проблемы?

**Comment by interlark** [comment]
Привет. Так сделать нельзя, т.к. изначально парсер написан больше в помощь маркетинговым исследованиям в рамках города или ряда городов. К тому же не все здания имеют вкладку "В здании" со списком всех организаций в нём.

Такие случаи имеют ссылку следующего характера: https://2gis.ru/<city_id>/inside/<building_id> 
Например, [https://2gis.ru/perm/inside/2252435468874737](https://2gis.ru/perm/inside/2252435468874737)

И парсятся заменой валидации URL'а организации
https://github.com/interlark/parser-2gis/blob/eaa09a2980dbcbb6bbe38a662fc7aaa7076a195c/parser_2gis/parser/parser.py#L51
На что-то вроде 
```python
        def valid_link(node: DOMNode) -> bool:
            if node.local_name == 'a' and 'href' in node.attributes:
                link_match = re.match(r'.*/firm/.*', node.attributes['href'])
                return bool(link_match)
```
Плюс прокрутка списка для экстракта ссылок организаций.
Возможно, в будущем добавлю. Идея хорошая.

**Comment by interlark** [comment]
Уточнил, вкладки "В здании" не имеют разве что частные дома и адреса где их просто нет. 
В [v0.1.9](https://github.com/interlark/parser-2gis/releases/tag/v0.1.9) появилась поддержка парсинга списка организаций в здании с помощью таких ссылок. См. [wiki](https://github.com/interlark/parser-2gis/wiki/URLs).

**Comment by YAGAOFFIT** [comment]
Спасибо большое за такой оперативный отзыв на мою проблему! Это большого
стоит, так держать)

пт, 19 авг. 2022 г., 00:56 Andy Trofimov ***@***.***>:

**Comment by meriler** [comment]
парочку зданий спарсил успешно, но на ссылке https://2gis.ru/spb/inside/5348660212758770 после Ситилинка заканчивает поиск, хотя организаций в здании ещё очень много

**Comment by interlark** [comment]
https://user-images.githubusercontent.com/20641837/197603423-e1da7983-404e-43c8-951b-3e8b59b633ad.mp4

В здании 133 организации, повторить описанную проблему не получилось. Убедитесь, что используете российский IP адрес.
