### ISSUE TITLE
При большой выгрузке свыше 1000 строк зависает 

### ISSUE THREAD

**Issue by Roman00591** [interlark/parser-2gis#16]
Парсер очень крутой. Мне очень понравился. Столкнулся с проблемой при выгрузке свыше 1000 строк. Зависает браузер. и перестает грузить новые строки. Пробывал на 2 машинах результат аналогичный. 1100-1300 строк выгружает а потом зависает если получиться поправить будет очень круто))). Спасибо за хороший и удобный софт

**Comment by interlark** [comment]
1000 позиций зависают с одной ссылки? На сколько по времени зависает?

1000 позиций занимают всего где-то 3GB RAM, дело вряд ли в памяти.
Скиньте URL на котором можно потестить эту проблему.

**Comment by Roman00591** [comment]
https://2gis.ru/moscow/search/Доставка готовых блюд/rubricId/1203 

На этой ссылке точно зависает при 

зависает и не дальше не грузит вообще.

**Comment by interlark** [comment]
Запустил парсер, спарсил по ссылке 2410 записей пока оперативная память не закончилась, это около 200 страниц поиска. Ошибки не увидел.

По поводу возможности продолжить работу парсера с определенной страницы идея неплохая.

**Comment by NaisTuMitYu** [comment]
Пример ссылки с 18 тыс. строками: Москва, ногтевые студии. Трудно сказать сколько надо оперативки под такое, похоже больше 10gb. Выход - по достижении лимита ОЗУ закрывать ссылку, запоминая номер страницы, если это возможно.

**Comment by interlark** [comment]
18 тысяч записей, действительно, могут занять около 9-10 GB RAM.

В [v1.1.0](https://github.com/interlark/parser-2gis/releases/tag/v1.1.0) добавлена автоматическая навигация к странице, если в [URL](https://github.com/interlark/parser-2gis/wiki/URLs) есть параметр страницы `/page/<номер_страницы>`.

Парсинг ссылки `https://2gis.ru/moscow/search/ногтевые студии` с определённой страницы теперь возможен, если добавить страницу в URL `https://2gis.ru/moscow/search/ногтевые студии/page/100`.
