### ISSUE TITLE
Парсер может работать на сервере?

### ISSUE THREAD

**Issue by sparsimsite** [interlark/parser-2gis#17]
Здравствуйте. Спасибо за вашу работу. Можно ли загрузить парсер для работы на сервере?

**Comment by interlark** [comment]
Приветствую. Да, почему бы и нет, [тесты](https://github.com/interlark/parser-2gis/blob/main/tests/test_parser.py) же гоняются на headless серверах.

Тут есть 2 подхода:
1) Запускать браузер в обычном режиме, но в с виртуальным "дисплеем" через [Xvfb](https://en.wikipedia.org/wiki/Xvfb).
```
sudo apt-get install xvfb
Xvfb -ac :99 -screen 0 1280x1024x16 &
export DISPLAY=:99

pip install parser-2gis
parser-2gis -i "https://2gis.ru/moscow/search/Аптеки" -o results.csv -f csv --parser.max-records 1000
```

2) Запускать парсер с headless флагом.
```
pip install parser-2gis
parser-2gis -i "https://2gis.ru/moscow/search/Аптеки" -o results.csv -f csv --parser.max-records 1000 --chrome.headless yes
```

Тут стоит заметить, что второй подход менее надёжный, т.к. [Chrome](https://www.google.com/chrome/) запущенный в [headless](https://developer.chrome.com/blog/headless-chrome/) режиме в теории можно отследить со стороны 2GIS.

**Comment by sparsimsite** [comment]
Большое спасибо за совет по запуску парсера. По возможности постараюсь отблагодарить вас за труд)

**Comment by sparsimsite** [comment]
Первый способ отлично работает

**Comment by interlark** [comment]
Также серверу желательно находиться в РФ, т.к. при работе из других мест может прилететь каптча после нескольких запросов.

**Comment by DuckDrkx** [comment]
Привет, а можно ли как то получить фото заведений ?

**Comment by ShSamariddin** [comment]
Привет! Пытаюсь запустить parser-2gis на сервере, но сталкиваюсь с ошибкой во время клика на элемент:

`pychrome.exceptions.CallMethodException: calling method: DOM.resolveNode error: No node with given id found`
Судя по трейсбэку, это происходит внутри perform_click, когда вызывается resolveNode с backendNodeId. Похоже, что DOM-элемент исчезает или не успевает загрузиться к моменту клика.

Кто-нибудь сталкивался с этим? Как можно обойти это?

Буду благодарен за любые идеи
