### ISSUE TITLE
Перестает парсить на 5 странице 2ГИС

### ISSUE THREAD

**Issue by IvanHuman** [interlark/parser-2gis#19]
Здравствуйте!

IP Российский
Пробовал 2 разных IP

Ссылка сгенерирована в программе
[https://2gis.kz/nur_sultan/search/Продуктовые магазины/rubricId/373](https://2gis.kz/nur_sultan/search/%D0%9F%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82%D0%BE%D0%B2%D1%8B%D0%B5%20%D0%BC%D0%B0%D0%B3%D0%B0%D0%B7%D0%B8%D0%BD%D1%8B/rubricId/373)

В 2ГИС написано 1960 объектов.
Грузится только 37-40 организаций.

Если смотреть в 2ГИС, то парсится только 5 страниц с сайта. Дальше не идет.

Потом пишет «парсинг завершен» и все закрывается. 

Иногда пишет вот такую ошибку:
---------------------------
10:24:35.826 | Ошибка во время работы парсера.
Traceback (most recent call last):
  File "parser_2gis\writer\writers\csv_writer.py", line 172, in _extract_raw
  File "pydantic\main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 3 validation errors for CatalogItem
name_ex
  field required (type=value_error.missing)
org
  field required (type=value_error.missing)
rubrics
  field required (type=value_error.missing)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parser_2gis\runner\gui.py", line 69, in run
  File "parser_2gis\parser\parsers\main.py", line 222, in parse
  File "parser_2gis\writer\writers\csv_writer.py", line 153, in write
  File "parser_2gis\writer\writers\csv_writer.py", line 175, in _extract_raw
  File "parser_2gis\common.py", line 115, in report_from_validation_error
KeyError: 'name_ex' 

-------------------------
**Вопрос:** Что я делаю не так? Подскажите, как загрузить все 1690 объектов?

![Вот такую ошибку выдает после 5 страницы](https://user-images.githubusercontent.com/121844780/210301592-ec26b670-b4a2-4d64-bfd5-fab8c00c584e.jpg)

**Comment by interlark** [comment]
Привет, этот случай какое-то исключение, остальные нормально парсит?
Ошибка валидации API, в след. версии парсера надо получше выводить информацию о таких случаях.
Я попробовал запустить указанную ссылку - нормльно спарсило.
Браузер, случайно, не скрываете?

[issue19.csv](https://github.com/interlark/parser-2gis/files/10335079/issue19.csv)

**Comment by IvanHuman** [comment]
Можем по Вацап пообщаться?
+77058045513 Иван
Я в режиме онлайн сейчас запущу и покажу вам.
Кратко здесь отвечу:
А я другие категории не парсил, нужна была именно эта, продуктовые
магазины.
Браузер не скрываю, напрямую открывается Гугл хром.


вт, 3 янв. 2023 г., 14:33 Andy Trofimov ***@***.***>:

**Comment by IvanHuman** [comment]
Как я вам завидую, что у вас все парсит! И что вы сумели написать эту программу!
Но вот я сейчас попробовал другую категорию и опять, на 5 странице "парсинг завершен", закрылся Хром с 2ГИС и всё (( Опять только 37 организаций и всё ((
Можете помочь мне?

![5 страницу уже не парсит](https://user-images.githubusercontent.com/121844780/210327520-ac695651-2260-46ce-833d-798f21bf1468.jpg)

**Comment by interlark** [comment]
1) Попробуйте последнюю [версию парсера](https://github.com/interlark/parser-2gis/releases/tag/v1.1.0).
2) Убедитесь что у вас достаточно свободной RAM.

**Comment by interlark** [comment]
Странно, что [https://2gis.kz/nur_sultan](https://2gis.kz/nur_sultan) работает, 2GIS недавно внёс изменения и теперь это [https://2gis.kz/astana](https://2gis.kz/astana).
На первый взгляд, похоже что просто недостаточно RAM.

**Comment by IvanHuman** [comment]
Здравствуйте.
Проверил версию 1.
Не работает. На 5 странице 2ГИС пытается продолжать парсить, но не парсит. И не останавливается. Ошибки не выдает никакой. Пришлось вручную принудительно программу остановить.
Я думаю здесь дело не в моем компе, а просто программа не может обойти какое-то ограничение 2ГИС. И это ограничение срабатывает всегда на 5 странице на 37 организации.
И дело не в названии города, потестил Питер, все тоже самое, 5 страница и конец.

Но для чистоты эксперимента, вдруг я что-то делаю не так? Можете спарсить вот по этой ссылке организации, сколько штук у вас в итоге получится? 2ГИС показывает 3270 фирм. Сможете мне выслать файл Эксель?
[https://2gis.kz/nur_sultan/search/продукты](https://2gis.kz/nur_sultan/search/%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82%D1%8B)                                                  
![5 страницу все равно не парсит вер 1](https://user-images.githubusercontent.com/121844780/210911615-b0cf5901-ed5f-47c3-87a1-f0e0882fd319.jpg)

**Comment by IvanHuman** [comment]
Я не понимаю, а как у вас без задержки кликов идет парсинг? Если я ставлю такие же параметры как у вас по кликам, то сразу же появляется ошибка Authorization error.

А когда я ставлю задержку кликов 6000 миллисекунд, то парсинг идет, но опять только до 5 страницы. Дальше не парсит.



![5 страницу все равно не парсит вер 3](https://user-images.githubusercontent.com/121844780/210979995-e5602e7d-0c42-441e-b540-0d5c36ca4028.jpg)

**Comment by interlark** [comment]
Рад, что проблема разрешилась, за поддержку благодарю.
