### ISSUE TITLE
Ошибка при парсинге python

### ISSUE THREAD

**Issue by toleeck** [interlark/parser-2gis#20]
Может что-то доустановить нужно?? пробовал по разному (с рубриками, без, с запросом...) - всё время такая ошибка.
Во время запуска в соседнем окне открывается Хром, но там ничего не происходит, правда есть ошибка на ключ запуска.
постарался в одном скрине все вводные показать:
![2gisParser](https://user-images.githubusercontent.com/40557618/219380252-33000fa5-a3f1-4a3a-a6b7-ba6a1660703c.png)
при этом файл .csv создаётся, но пустой, в нём только названия полей.
пробовал предыдущий ваш релиз запускать, такой же результат.
спасибо.

**Comment by interlark** [comment]
Ничего доустанавливать не надо, только Chrome необходим. Если открывается Chrome, значит программа его находит. Но почему подключится не может - это большой вопрос, впервые такое вижу.

Chrome запускается со открытым портом удалённой отладки и программа к нему подключается. Теоретически, если Firewall смог помешать этому, то ошибка была бы примерно такой.

**Comment by toleeck** [comment]
Благодарю, вероятно дело именно в брандмауэре.
