### ISSUE TITLE
Доработка - дополнительная информация, возможно ли ее парсить?

### ISSUE THREAD

**Issue by kus54** [interlark/parser-2gis#22]
Добрый день!
рябята а можете еще дополнить:
1. реквизиты организаций, тех кто их указывает?
2. средний чек
Можно просто раздел Инфо брать там много что указывается
Прикладываю примеры:
![image](https://user-images.githubusercontent.com/89178859/222377199-27243a69-96b0-4082-ad00-11fb64a316b1.png)
![image](https://user-images.githubusercontent.com/89178859/222373038-5b4c9c37-2d73-4863-8c32-96cc2e939a14.png)

**Comment by interlark** [comment]
Привет, регистрационный номер, средний чек и пр. - слишком узкие аттрибуты, да и встречаются не у всех, но они приходят в API ответе сервера, можете сами их извлечь и сохранить себе в таблицу.

**Comment by kus54** [comment]
Добрый день!
Можете более подробно подсказать откуда именно забирать?

**Comment by interlark** [comment]
Подкорректируй [функцию](https://github.com/interlark/parser-2gis/blob/8805405649554df046e5c67d841eff1a9ef4afed/parser_2gis/writer/writers/csv_writer.py#L158) извлечения данных из ответа сервера, извлеки нужные данные: ОГРН, ОГРНИП обычно хранятся в атрибуте `warning_text`, если правильно помню. Средний чек тоже есть в разделе `org`.

Ну и останется только лишь объявить новые ключи данных в [маппинге](https://github.com/interlark/parser-2gis/blob/8805405649554df046e5c67d841eff1a9ef4afed/parser_2gis/writer/writers/csv_writer.py#L30).

Это всё.
