### ISSUE TITLE
v. 1.1.2

### ISSUE THREAD

**Issue by crysan** [interlark/parser-2gis#23]
Добрый!
Похоже версия нестабильна. Ограничение на объем памяти не работает.
Программа забирает всю свободную память и виснет.

**Comment by crysan** [comment]
https://disk.yandex.ru/i/xhL6vRJL4dJ1hg

**Comment by interlark** [comment]
Привет, не могу повторить проблему.
Выставил тестово 50 мегабайт ограничения RAM, парсинг URL [https://2gis.ru/perm/search/аптеки](https://2gis.ru/perm/search/аптеки) дал 37 строк и закончился по ограничению памяти.

Возможно, у тебя слишком высокий лимит памяти?

**Comment by interlark** [comment]
По скрину вижу необычную ситуацию, парсер даже не смог загрузиться в память (ещё до запуска браузера), т.к. RAM на этапе запуска уже израсходована.

**Comment by crysan** [comment]
Добрый!
Проблему нашел. При любой установки количества памяти и Лимита записи в 9999999 и Сложных колонок в 9999999
Съедается вся память и программа вылетает с ошибкой выше на скрине

**Comment by interlark** [comment]
Fixed by 937d92512584a09b47d859ecc315be49972a27e3
