### ISSUE TITLE
как работать на macOS? 

### ISSUE THREAD

**Issue by Danilrrrr** [interlark/parser-2gis#28]
Failed to load GUI: dlopen(/var/folders/xj/4wzr41z108lcz9df2p0635_w0000gn/T/_MEIyGDaBb/lib-dynload/_tkinter.cpython-38-darwin.so, 2): Library not loaded: /System/Library/Frameworks/UniformTypeIdentifiers.framework/Versions/A/UniformTypeIdentifiers
  Referenced from: /private/var/folders/xj/4wzr41z108lcz9df2p0635_w0000gn/T/_MEIyGDaBb/libtk8.6.dylib

такую ошибку выдает терминал 
куда копать?

**Comment by interlark** [comment]
Какая версия MacOS?

**Comment by Danilrrrr** [comment]
> Какая версия MacOS?

10.15.7 catalina

**Comment by Danilrrrr** [comment]
Parser2GIS: ошибка: следующие аргументы обязательны: -i/--url, -o/--output-path, -f/--format

вот такую ошибку выдает в конце, но он даже не дает ввести эти аргументы

**Comment by interlark** [comment]
Скорее всего, ты установил консольную версию парсера с помощью менеджера пакетов pip: ```pip install parser-2gis```
GUI можешь установить так: ```pip install parser-2gis[gui]```

**Comment by Danilrrrr** [comment]
а я из релизов взял вообще, через pypl вообще не умею ставить( ну ладно попробую разобраться, спасибо большое

**Comment by Danilrrrr** [comment]
короче он через pypl ставит только parser-2gis, а parser2gis[gui] не ставит, выдает ошибку: zsh: no matches found: parser-2gis[gui]

**Comment by Danilrrrr** [comment]
может там че сломалось в библиотеке для mac os
я думал что я не правильно что то делаю и решил поставить без gui и он поставился через Pip а с gui выдает ошибку

**Comment by Danilrrrr** [comment]
при этом на винде все работает отлично не единой проблемы за неделю

**Comment by kishman1** [comment]
Помогите пожалуйста запустить мне на маке каталине, я вообще далек от программирование и у меня такая же ошибка когда я скачиваю одним файлом

**Comment by interlark** [comment]
Дубликат #45, нет macOS для тестов. Нужны разработчики с macOS.
