### ISSUE TITLE
Вытащить все здания в городе

### ISSUE THREAD

**Issue by AlimTleuliyev** [interlark/parser-2gis#31]
Здравствуйте, столкнулся с задачей вытащить абсолютно информацию о всех здания в определенном городе.

Парсеру нужно писать запросы типа https://2gis.ru/moscow/search/Поесть

Можно ли как нибудь написать запросы чтобы вытащить всю Москву?

**Comment by AlimTleuliyev** [comment]
Здания нужны для того чтобы далее вытащить информацию о высоте здания. Насколько я понял сейчас парсер не вытаскивает данные о высоте, хотя в тугисе есть 3Д мод и там визуализируется высота то есть она есть. Можете подсказать как можно вытащить данные о высоте зданий тоже?

**Comment by olga-kryuchkova-00** [comment]
Здравствуйте! Подскажите, пожалуйста, получилось ли решить вашу задачу с помощью данного парсера? Или может получилось достать данные о высоте (или этажности) зданий другим способом?

**Comment by AlimTleuliyev** [comment]
@olga-kryuchkova-00 Здравствуйте, нет к сожалению не вышло(
