### ISSUE TITLE
не возможно пройти капчу

### ISSUE THREAD

**Issue by ehdikorl** [interlark/parser-2gis#32]
После загрузки 10 страниц, вылезает капча, на которой не грузятся изображения
![image](https://github.com/interlark/parser-2gis/assets/117590479/de98a9e4-7349-4e04-9531-2a4379a51b49)
, ели эту капчу открыть в другой вкладке то все работает, но приложение заканчивает работу
![image](https://github.com/interlark/parser-2gis/assets/117590479/31138c11-ee64-43a5-946a-76a4d0fd025d)

**Comment by interlark** [comment]
Привет. Да, видимо, 06.07.23 2GIS решил ввести капчу, т.к. слишком много людей стали использовать парсер и компания стала чувствовать убытки. Единственный выход - это подключение captcha-resolver сервиса, например [anti-captcha](https://anti-captcha.com). Если свободное время - сделаю, да и pull реквесты приветствуются.

**Comment by interlark** [comment]
Кто-нибудь пробовал играть с задержкой, как бо́льших задержках реагирует 2GIS?

**Comment by mister20123** [comment]
всем привет да я играл с задержкой с 1до 20 ни помогло

**Comment by alexcrazy95** [comment]
Попробовал задержку и 500 и 1000 и 2000 и 4000 всё равно вылетает капча, потом как только её введёшь 1 страница собирается и парсинг этого города завершается хотя там ещё страниц 10 может быть

**Comment by muzzaleeni** [comment]
Там не зависит от задержки. У меня сработало таким образом:

- --chrome.disable-images yes
- --parser.delay_between_clicks {любое}
- Когда открывается Google Chrome window, самостоятельно открываете еще раз в другом tab.
- В том же tab триггерите капчу и решаете. Это повлияет на триггер капчи в основном tab и он не будет вылазит. По крайней мере, у меня так сработало.

**Comment by karibays** [comment]
> 
В том же хроме открыть другую вкладку и там решить?

**Comment by muzzaleeni** [comment]
> > 
> 
> В том же хроме открыть другую вкладку и там решить?

Да!

**Comment by alexcrazy95** [comment]
> Там не зависит от задержки. У меня сработало таким образом:
> 
> * --chrome.disable-images нет
> * --parser.delay_between_clicks {любое}
> * Когда открывается окно Google Chrome, открывается вкладка "Еще раз в компьютере".
> * В том же tab триггерите капчу и решаете. Это повлияет на триггер капчи в основном на вкладке и он не будет вылазит. По случаю, у меня так сработало.
> 
> _Капчу решаете самостоятельно!_

Капча решается и город не парсится дальше, 1 страницу выдачи собирает а их ещё 10 может быть и оп, новый город парсит

**Comment by bringmetheural** [comment]
> > Там не зависит от задержки. У меня сработало таким образом:
> > 
> > * --chrome.disable-images нет
> > * --parser.delay_between_clicks {любое}
> > * Когда открывается окно Google Chrome, открывается вкладка "Еще раз в компьютере".
> > * В том же tab триггерите капчу и решаете. Это повлияет на триггер капчи в основном на вкладке и он не будет вылазит. По случаю, у меня так сработало.
> > 
> > _Капчу решаете самостоятельно!_
> 
> Капча решается и город не парсится дальше, 1 страницу выдачи собирает а их ещё 10 может быть и оп, новый город парсит

Такая же проблема, кажется, что можно обойти в случае, если добавить условие по парсингу определенного количества страниц выдачи, новому открытию окна браузера и начала парсинга со следующей страницы, относительно которой закончили. Но это надо кодить))0)

**Comment by Phoenixbay0001** [comment]
> Там не зависит от задержки. У меня сработало таким образом:
> 
> * --chrome.disable-images no
> * --parser.delay_between_clicks {любое}
> * Когда открывается Google Chrome window, самостоятельно открываете еще раз в другом tab.
> * В том же tab триггерите капчу и решаете. Это повлияет на триггер капчи в основном tab и он не будет вылазит. По крайней мере, у меня так сработало.
> 
> _Капчу решаете самостоятельно!_

К сожалению не помогает, капча не триггерится =(

**Comment by Phoenixbay0001** [comment]
> Привет. Да, видимо, 06.07.23 2GIS решил ввести капчу, т.к. слишком много людей стали использовать парсер и компания стала чувствовать убытки. Единственный выход - это подключение captcha-resolver сервиса, например [anti-captcha](https://anti-captcha.com). Если свободное время - сделаю, да и pull реквесты приветствуются.

У кого-нибудь получилось прикрутить антикапчу ?

**Comment by MetaMorfus** [comment]
Интересно, что продолжает парсить до конца страницы, после решения капчи. 
После чего завершает парсинг...
![изображение](https://github.com/interlark/parser-2gis/assets/140005094/4d4df6ad-fe1d-4238-b868-76e00c053684)

**Comment by PaperWoo** [comment]
Способ с решением капчи на другой странице хром — рабочий.

**Comment by PaperWoo** [comment]
Способ с решением капчи в другом окне браузера работает.

Начинаете парсить, сразу же как открывается браузер копируете ссылку и открываете второе окно. После начинаете листать по страницам, тем самым вы триггерите капчу. Решаете капчу и не открывайте первую страницу (ниже объяснил почему страницу открывать не стоит). После этих манипуляций капча появляться перестанет, по крайней мере я проверял на 1200 организациях и она не появлялась.

Не знаю как у вас, но у меня бывает парсер может перейти в конкретную организацию и закончить парсить, но если не находиться на странице, где происходит парсинг, то вы не столкнетесь с этой проблемой.

**Comment by AntonShutov1** [comment]
> Способ с решением капчи в другом окне браузера работает. В настройках парсера главное не забыть включить отображение изображений на странице, иначе вы просто не сможете решить капчу.
> 
> Начинаете парсить, сразу же как открывается браузер, копируете ссылку и открываете второе окно. После начинаете листать по страницам, тем самым вы триггерите капчу. Решаете капчу и не открывайте первую страницу (ниже объяснил почему страницу открывать не стоит). После этих манипуляций капча появляться перестанет, по крайней мере я проверял на 1200 организациях и она не появлялась.
> 
> Не знаю как у вас, но у меня бывает парсер может перейти в конкретную организацию и закончить парсить, но если не находиться на странице, где происходит парсинг, то вы не столкнетесь с этой проблемой.

Сейчас ворк?У меня перестает парсить

**Comment by PaperWoo** [comment]
> > Способ с решением капчи в другом окне браузера работает. В настройках парсера главное не забыть включить отображение изображений на странице, иначе вы просто не сможете решить капчу.
> > Начинаете парсить, сразу же как открывается браузер, копируете ссылку и открываете второе окно. После начинаете листать по страницам, тем самым вы триггерите капчу. Решаете капчу и не открывайте первую страницу (ниже объяснил почему страницу открывать не стоит). После этих манипуляций капча появляться перестанет, по крайней мере я проверял на 1200 организациях и она не появлялась.
> > Не знаю как у вас, но у меня бывает парсер может перейти в конкретную организацию и закончить парсить, но если не находиться на странице, где происходит парсинг, то вы не столкнетесь с этой проблемой.
> 
> Сейчас ворк?У меня перестает парсить

Да, сегодня проверил, работает полностью

**Comment by interlark** [comment]
Как уже упоминал в #33, капчу сервис убрал.
