### ISSUE TITLE
Ждем обновлений от прекрасного нашего разработчика)  вот только начал внедрять эту прогу в работу. недолго продлилось)

### ISSUE THREAD

**Issue by akerman45023** [interlark/parser-2gis#33]
Привет. Да, видимо, 06.07.23 2GIS решил ввести капчу, т.к. слишком много людей стали использовать парсер и компания стала чувствовать убытки. Единственный выход - это подключение captcha-resolver сервиса, например [anti-captcha](https://anti-captcha.com). Если свободное время - сделаю, да и pull реквесты приветствуются.

_Originally posted by @interlark in https://github.com/interlark/parser-2gis/issues/32#issuecomment-1624839464_

**Comment by akerman45023** [comment]
Раньше до 9 тыс компаний парсил. а сейчас до 200 еле набирает((((

**Comment by alexcrazy95** [comment]
+++ хорошая программа)

**Comment by rodnovspb** [comment]
хотя бы чтобы вручную можно было капчу вводить и он продолжал с места остановки

**Comment by alexcrazy95** [comment]
> хотя обычно можно было капчу вводить и он продолжал с места остановки

согласен))

**Comment by Bananizzz** [comment]
Очень ждем!

**Comment by MetaMorfus** [comment]
Если можно, то хотя бы сделать продолжение с места остановки, пожалуйста. Капчу можно и пощелкать при желании.

**Comment by hojon** [comment]
парсинг мертв

**Comment by dastan1910** [comment]
Да, ждем обновлений, спасибо!

**Comment by murXman** [comment]
Ждем обновления, спасибо! Согласен что капчу можно и руками ввести. Главное чтобы парсер не падал после нее

**Comment by interlark** [comment]
Капча была введена 2gis экспериментально -- сейчас её уже нет, поэтому этот issue закрыт.

**Comment by zeliboba7** [comment]
Опять капча появляется, конечно не сразу, но со страницы 200-300 стабильно. Большие задержки между кликами не помогают, рандомное увеличение задержки тоже. Когда капча появляется, парсер работу не прекращает, а продолжает перебирать страницы, но через некоторое хромиум сообщает "Aw, Snap!" и `Error code: SIGTRAP`. 

Прохождение капчи в ручном режими очень неудобно, когда программа запускается в консольном режиме, а  подключение сторонних сервисов для разгадывания капчи может быть сложно. В качестве промежуточного решения было бы здорово, если бы при появлении требования капчи консольная версия завершала работу и возвращала номер последней успешной страницы, чтобы после можно было перезапустить и продолжить со следующей страницы.
