### ISSUE TITLE
Pydantic version

### ISSUE THREAD

**Issue by Phinnik** [interlark/parser-2gis#39]
В зависимостях проекта лежит `pydantic>=1.9.0`
На версии pydantic > 2.0.0 вылетают разные ошибки.
Необходимо зафиксировать более четкую версию

**Comment by zeliboba7** [comment]
Подтверждаю:  `pip install parser-2gis` ставит  `pydantic-2.6.0` и `pydantic_core-2.16.1`, при запуске выдает ошибку. Если их удалить и поставить `pip install pydantic~=1.9` (ставит `pydantic-1.10.14`), то ошибок нет.

**Comment by interlark** [comment]
Fixed by 937d92512584a09b47d859ecc315be49972a27e3
