### ISSUE TITLE
Возможен парсинг ссылок типа "https://2gis.ru/firm/70000001036976412" ?

### ISSUE THREAD

**Issue by NaisTuMitYu** [interlark/parser-2gis#40]

**Comment by interlark** [comment]
Нет, и вряд ли будет реализован. Парсер основан на перехвате API гидрации, а не на экстракте сущостей из SSR страницы. Да и никогда не встречал нужды собирать отдельные страницы.
Такой парсер вы сможете сами сделать, все полезные данные будут в переменной `__customcfg` страниц компания типа [https://2gis.ru/firm/70000001036976412](https://2gis.ru/firm/70000001036976412)

**Comment by interlark** [comment]
Будет реализовано в v1.2.0
