### ISSUE TITLE
максимальное количество записей

### ISSUE THREAD

**Issue by WormMad** [interlark/parser-2gis#42]
Скажите а можно обойти ограничение на максимальное количество записей в выгрузке? 
"| Парсинг [2800] > Wildberries
| Спарсено максимально разрешенное количество записей с данного URL."

**Comment by interlark** [comment]
Да, в настройках.
Значение по-умолчанию выставляется автоматически, в зависимости от количества RAM установленной в системе.
Можно поменять, но с осторожностью.
