### ISSUE TITLE
Вопрос по Google Maps и Яндекс Картам

### ISSUE THREAD

**Issue by negeloT** [interlark/parser-2gis#47]
interlark, здравствуйте!

Очень благодарен за Ваш проект. Безумно крутую вещь Вы сделали.
Подскажите, пожалуйста, а не встречалось ли Вам что-то похожее по Google Maps или Яндекс Картам?
Или есть ли у Вас в планах разработка подобного для других сервисов? 

С уважением, 
negeloT

**Comment by maxibon228** [comment]
было бы круто . Если найдёшь подобный проэкт отпишись сюда пожалуйста.

**Comment by interlark** [comment]
По вопросам не касающихся этого проекта, лучше писать на почту.
