### ISSUE TITLE
не собирает контакты

### ISSUE THREAD

**Issue by OlegOgran** [interlark/parser-2gis#48]
зачем он нужен, если только названия и режим работы собирает

**Comment by interlark** [comment]
В [вики](https://github.com/interlark/parser-2gis/wiki/%D0%94%D0%B5%D0%BC%D0%BE%D0%BD%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F) есть [пример](https://github.com/interlark/parser-2gis/files/8750364/tattoo_parlors_of_russia.csv) собранных данных.

Там же есть [список данных](https://github.com/interlark/parser-2gis/wiki/CSV-%D0%B8-XLSX-%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D1%8B), который он собирает:

- Наименование _`Наименование`_
- Описание _`Описание`_
- Список закрепленных рубрик _`Рубрики`_
- Адрес _`Адрес`_
- Комментарий к адресу _(офис, этаж, и т.д.)_ _`Комментарий к адресу`_
- Почтовый индекс _`Почтовый индекс`_
- Микрорайон, район, город, округ, регион, страна _`Микрорайон`_, _`Район`_, _`Город`_, _`Округ`_, _`Регион`_, _`Страна`_
- Часы работы _`Часы работы`_
- Часовой пояс _`Часовой пояс`_ 
- Рейтинг _(От 0 до 5)_ _`Рейтинг`_ 
- Количество отзывов _`Количество отзывов`_ 
- Номера телефонов _`Телефон 1`_, _`Телефон 2`_, _`Телефон 3`_, _и т.д._
- E-mail адреса _`E-mail 1`_, _`E-mail 2`_, _`E-mail 3`_, _и т.д._
- Адреса веб-сайтов _`Веб-сайт 1`_, _`Веб-сайт 2`_, _`Веб-сайт 3`_, _и т.д._
- Instagram _`Instagram 1`_, _`Instagram 2`_, _`Instagram 3`_, _и т.д._
- Twitter _`Twitter 1`_, _`Twitter 2`_, _`Twitter 3`_, _и т.д._
- Facebook _`Facebook 1`_, _`Facebook 2`_, _`Facebook 3`_, _и т.д._
- ВКонтакте _`ВКонтакте 1`_, _`ВКонтакте 2`_, _`ВКонтакте 3`_, _и т.д._
- WhatsApp _`WhatsApp 1`_, _`WhatsApp 2`_, _`WhatsApp 3`_, _и т.д._
- Viber _`Viber 1`_, _`Viber 2`_, _`Viber 3`_, _и т.д._
- Telegram _`Telegram 1`_, _`Telegram 2`_, _`Telegram 3`_, _и т.д._
- YouTube _`YouTube 1`_, _`YouTube 2`_, _`YouTube 3`_, _и т.д._
- Skype _`Skype 1`_, _`Skype 2`_, _`Skype 3`_, _и т.д._
- Широта _(В системе [WGS84](https://ru.wikipedia.org/wiki/WGS_84))_ _`Широта`_ 
- Долгота _(В системе [WGS84](https://ru.wikipedia.org/wiki/WGS_84))_ _`Долгота`_
- Ссылка в 2GIS _`2GIS URL`_
