### ISSUE TITLE
Парсинг автобусных остановок из 2ГИС

### ISSUE THREAD

**Issue by negeloT** [interlark/parser-2gis#52]
Здравствуйте!
Подскажите, пожалуйста, а как можно парсить автобусные остановки? 
Я в поисковике Вашего приложения вбиваю "остановка" без рубрики, он находит 1000+ остановок, но, к сожалению, не начинает их парсить. Подскажите, как можно исправить это?
Заранее благодарю!

**Comment by interlark** [comment]
Добавлена поддержка парсинга остановок в [v1.2.1](https://github.com/interlark/parser-2gis/releases/tag/v1.2.1).

**Comment by Krupko** [comment]
![1](https://github.com/user-attachments/assets/a61090b0-32ea-49c3-8a78-7fe7ade163f6)
Добрый день!
после переустановки системы Linux mint выдает такую ошибку после запускаподскажите как победить.
До этого все работало без проблемм)

**Comment by Advisor333** [comment]
Здравствуйте! Благодарю за парсер! Подскажите как сделать ранжирование, например, вывод только емайл адресов?

**Comment by Zhanara2024** [comment]
Здравствуйте скачала релиз на мак но мне выдает ошибку и не открывается парсер, подскажите как установить его?
<img width="1440" alt="Снимок экрана 2024-12-06 в 09 02 15" src="https://github.com/user-attachments/assets/f3a7c321-806a-4ed3-8600-4f8ba7deca7d">
Вот такое окошко выходит и все на этом

**Comment by Abrorbek19** [comment]
Здравствуйте, я не смог использовать эту программу на Mac, появляются ошибки, ткинтер или приложение не открываются
