### ISSUE TITLE
Парсер парковок

### ISSUE THREAD

**Issue by AleksVB81** [interlark/parser-2gis#53]
URL https://2gis.ru/nalchik/search/Парковка/filters/sort=name
почему не сохраняется информация о вместимости - количество мест
например https://2gis.ru/nalchik/search/%D0%BF%D0%B0%D1%80%D0%BA%D0%BE%D0%B2%D0%BA%D0%B8/geo/70030076167674212/43.604498%2C43.480896?m=43.602641%2C43.48471%2F14.88
Спасибо.

**Comment by interlark** [comment]
Тут проще собирать в JSON и конвертировать в удобный формат после сбора.
