### ISSUE TITLE
Ошибка закрытия браузера

### ISSUE THREAD

**Issue by Proteus86** [interlark/parser-2gis#7]
16:24:23.000 | Парсинг ссылки завершён.

16:24:23.000 | Вкладка браузера была закрыта.

16:24:23.022 | Парсинг завершён.
При работе парсера иногда возникает данная ошибка. 
К сожалению не знаю как узнать о ней больше и приложить логи.

**Comment by interlark** [comment]
Это нормальное поведение. Вот цитата из документации:

>Парсер сам пытается определить **Лимит RAM** и **Лимит записей**, но можно вручную задать больше. Судя по тестам, **4GB RAM** хватает на **2000 записей**, **6GB RAM** хватает на **3000 записей**. Если браузер съедает всю доступную ему память - он выгружается из памяти, парсинг ссылки завершается, парсер переходит к следующей ссылке, если она есть.

Такую ошибку можно встретить когда браузер съедает всю доступную ему память и "закрывает" вкладку или когда пользователь сам закрывает её.

В Вашем случае могу посоветовать установить лимит памяти побольше или запустить парсер на машине с бо́льшей оперативной памятью.

**Comment by interlark** [comment]
Но да, я заметил что в коде нет передачи парсеру следующей ссылки в таких ситуациях. Следует поправить.

**Comment by Proteus86** [comment]
У меня стоит лимит 10GB оперативной памяти и 6000 ссылок. Да возможно с этим и связано . Так как получается на 6000 записей требуется 12GB оперативной памяти .

**Comment by Proteus86** [comment]
09:27:37.463 | Парсинг [3889] > Nujoom Al Shimal Textiles & Gents

09:27:52.695 | Парсинг ссылки завершён.

09:27:52.695 | Вкладка браузера была закрыта.

09:27:52.736 | Парсинг завершён.
Вообщем словил ошибку без переполнения оперативной памяти.

**Comment by Proteus86** [comment]
На данный момент наблюдал смерть браузера ) 
Вообщем точно не лимит оперативы. 
Использование проца подскочило. Парсинг ссылок сильно замедлился. 
Судя по диспетчеру задач несколько процессов гуглохрома запущено, но почти 5,5GB оперативной памяти ушло в один из процессов .
В теории догадки может не отрабатывать сборщик мусора в гугло хроме . 
В CLI есть параметр сборщика(он отключен так как гугл хром предоставляет свой ) , но в  GUI его нет .

**Comment by interlark** [comment]
> На данный момент наблюдал смерть браузера )

Так она выглядела?
![WvbHw](https://user-images.githubusercontent.com/20641837/177586786-92630813-f01f-4d6d-af34-0fef3f673756.png)

Я тестировал сборщик в последних версиях Chrome браузера на Windows и Linux, он хорошо отрабатывает.
Если лимит RAM в настройках указан, он его придерживался. В Вашем случае значение для RAM должно быть `12000`.

Могу посоветовать попробовать при запуске парсера закрыть все открытые браузеры Chrome на компьютере.

Также можно попробовать установить лимит RAM в `10` и посмотреть умрёт ли сразу браузер, чтобы удостовериться что лимиты читаются и работают.

И да, насколько я знаю, Chrome не умеет использовать файл подкачки - он опирается только лишь на физический объем оперативной памяти исключая размер swap файла на любых ОС.

**Comment by Proteus86** [comment]
Очень часто проявляется эта ошибка на городе Алматы или на Дубай. Насколько я понимаю там оооочень много данных по каждой ссылке . И браузер не выдерживает и отваливается .

**Comment by interlark** [comment]
Проверил парсинг в Дубае на популярном запросе "аптеки", на разных компьютерах под Linux и Windows.

`2839 записей` стоили около `6GB RAM` браузеру Chrome. Лимиты RAM заданные парсером браузеры отлично слушают.
 
Если у Вас падает браузер, то решайте вопрос с памятью, с парсером проблем нет.

![parser-2gis_dubai_one](https://user-images.githubusercontent.com/20641837/177960203-f0c41bdc-16a8-415f-99a8-1b920222b537.png)
![parser-2gis_dubai_two](https://user-images.githubusercontent.com/20641837/177960210-a4618699-6d06-4332-861b-78ab9a40ef47.png)
