### ISSUE TITLE
TypeError: the JSON object must be str, bytes or bytearray, not dict

### ISSUE THREAD

**Issue by Proteus86** [interlark/parser-2gis#9]
10:50:06.731 | Ошибка во время работы парсера.
Traceback (most recent call last):
  File "parser_2gis\gui\app.py", line 83, in run
  File "parser_2gis\parser\parser.py", line 204, in parse_url
  File "json\__init__.py", line 339, in loads
TypeError: the JSON object must be str, bytes or bytearray, not dict

при попытке спарсить
10:49:37.274 | Парсинг ссылки https://2gis.ru/dubai/search/Обои/rubricId/556

**Comment by interlark** [comment]
Повторить ошибку не удалось:

https://user-images.githubusercontent.com/20641837/177507263-4284ae26-a9b8-4043-b0dc-40f96ce6e264.mp4


Хотя такой исход возможен при неудачной попытке переполучения нового ключа. Спасибо за отчёт, недоглядел - поправлю.
